### PR TITLE
OpenAPI Docs

### LINKED ISSUE #22: API Docs
# Summary

API documentation is required to allow clients to know how to interface with the REST API endpoints of this service.

### PR DESCRIPTION
**Pull request by BrianLusina**
# Description

This adds OpenAPI specification for the API allowing clients to view & test the exposed REST API.

Fixes #22

## Resolution/What did you add?

- Swagger OpenAPI specification
- Removed unnecessary info logging
- Add new config `DocsEnabled` which is a flag used to indicate whether to display docs page or not.
- Additional tests for register handler

## Additional Release Steps

None

## How can we test this?

- Run `docker compose up`
- Run application with`make run`
- Navigate to API docs on http://localhost:8085/docs/index.html
- View the API documentation

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new errors
- [x] Is my code backwards compatible

### CODE REVIEW

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dd0df54e75ea394e58d5f5cb89f4b0d85a825f5c
</p>

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 47b0a6fbf1516303f0ff9bd761c007c1ec7314b4
</p>

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1f336e750c60854c7d473dbd9d7677bd45c13d16
</p>

**Comment by BrianLusina** [comment]
@DevAgani API docs are done & how to access these docs can be found in the PR description or in the API docs file under the docs folder

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1fbe92af2910bc36a55e324c3252842d8ce9eb8c
</p>

**Pull request merged**
