### PR TITLE
Authentication refresh tokens

### LINKED ISSUE #14: Authentication Refresh Tokens
# Summary

Currently on user login, only an access token is generated which has a limited validity period. Which forces, clients/users to request a new access token by logging in again. This does not provide for a very good user experience. There needs to be a refresh token that's also provided when a user logs in that has a longer validity period that allows clients to access a new access token without requiring to login again.

## Functional Requirements

Refresh tokens created should have an extended validity period that is more than the access token's validity period. The newly created refresh token should have information of the user that allows generating a new access token. 

## Implementation Notes

There is an authentication  jwt utility that handles generation of new access tokens(this can be found [here](https://github.com/SanctumLabs/curtz/blob/main/app/pkg/jwt/jwt.go#L16)). This should be extended to add generation of refresh tokens when the user is logging in.

The function currently looks like this:

```go

func Encode(uid string, signingKey string, issuer string, expireDelta int) (string, error) {
	claims := Claims{
		StandardClaims: jwt.StandardClaims{
			ExpiresAt: time.Now().Add(time.Minute * time.Duration(expireDelta)).Unix(),
			IssuedAt:  time.Now().Unix(),
			Issuer:    issuer,
			Subject:   uid,
		},
		UserId: uid,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	return token.SignedString([]byte(signingKey))
}
```

This should be extended to add creation of refresh tokens and the return type changed to also include the refresh token, ideally a custom type can be returned(a struct preferably), a map would do as well with the key as the type of token and the value the actual token.

This function is used in the `AuthService` method `GenerateToken` that can be found [here](https://github.com/SanctumLabs/curtz/blob/main/app/internal/services/auth/auth.go#L23) and looks like below:

```
func (svc *AuthService) GenerateToken(userId string) (string, error) {
	return jwt.Encode(userId, svc.config.Jwt.Secret, svc.config.Jwt.Issuer, svc.config.ExpireDelta)
}
```
Note the return type here is a tuple of the types `string and error`. This will need to be changed appropriately as well.

This is an implementation of the interface found [here](https://github.com/SanctumLabs/curtz/blob/main/app/internal/core/contracts/services.go#L10):

``` go
type AuthService interface {
	// Authenticate a user given the token. Returns user id if authenticated, error otherwise.
	Authenticate(token string) (string, time.Time, error)
	// GenerateToken generates a user token provided the user id
	GenerateToken(userId string) (string, error)
}
```

Note that you will only need to change the `GenerateToken` function.

The Login endpoint that already exists should be extended to include a new field in the response `refresh_token` that contains the new refresh token:

``` json
{
	"id": "<USER_ID>",
	"email": "johndoe@example.com",
	"created_at": "2022-07-07T05:07:17.904Z",
	"updated_at": "2022-07-07T05:07:17.904Z",
	"access_token": "<ACCESS_TOKEN>",
        "refresh_token": "<REFRESH_TOKEN>"
}
```

> Sample Payload, the fields enclosed in `<>` will be populated & will be actual values. 

This payload can be found [here](https://github.com/SanctumLabs/curtz/blob/main/app/api/v1/auth/dto.go#L15):

```go
type userResponseDto struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	AccessToken string    `json:"access_token,omitempty"`
}
```
A new field will need to be added to include a `RefreshToken`

Further, the handler for login found [here](https://github.com/SanctumLabs/curtz/blob/main/app/api/v1/auth/handlers.go#L34) should be updated to include adding the refresh token as part of the response:

```go
// other handler code
       token, err := hdl.authSvc.GenerateToken(user.ID.String())

	if err != nil {
		ctx.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"message": "Invalid Email or Password"})
		return
	}

	response := userResponseDto{
		ID:          user.ID.String(),
		Email:       user.Email.Value,
		CreatedAt:   user.CreatedAt,
		UpdatedAt:   user.UpdatedAt,
		AccessToken: token,
	}

	ctx.JSON(http.StatusOK, response)
} 
```

> this will also need to be update to return the appropriate refresh token.

## Acceptance Criteria

1. On user login, a `refresh_token` should be returned as part of the response.
2. Refresh tokens should have a longer validity period over access tokens
3. Refresh tokens should only contain information that can be decoded to get information of the user, an id will suffice. No further claims are needed for this token.
4. Refresh tokens CAN NOT be used to access resources that require an access token. For example, it should not be possible to use a refresh token to create a new shortened URL. This should always return an Unauthorized Response.

### PR DESCRIPTION
**Pull request by BrianLusina**
# Description

Adds a refresh token to login endpoint as part of a response. This refresh token can be used to request a new access token.

Fixes #14 

## Resolution/What did you add?

- Update JWT library package to generate refresh token
- Add configurable refresh token expiry delta, defaults to 1 hour
- Extend AuthService to generate refresh token
- Update login http handler to return response with refresh token

## Additional Release Steps

No new additional steps required.

## How can we test this?

1. Run Unit tests with `make test`
2. To run manual tests first run `docker compose up` or `docker-compose up` depending on the platform used.
3. Then run the application with `make run`
4. Make a request to register a new user(if none already exists) to the `/api/v1/curtz/register` endpoint
5. With the newly created user, perform a login request on the endpoint `api/v1/curtz/login`, the response will contain a refresh token as part of the response.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new errors
- [x] Is my code backwards compatible
- [x] Have I written unit tests

### CODE REVIEW

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e35425992b4c17b5c29e55ad900df0435458bd2e
</p>

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 23d57bc77ac1d9ebe7fb4243199bb4edac86ebf6
</p>

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9701545dc1cb3112262b64840f6c096aca86f17
</p>

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ee1db939e173561a534543f6207634f8ff267d89
</p>

**Comment by ratholos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: Big PR</td>
    </tr>
  </tbody>
</table>


>: Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fc2ef484a2bc7d64401fcd13133a60193e9dc040
</p>

**Review by DevAgani — APPROVED** [review]

**Pull request merged**
